feat: refactored code; fixed brew; v3.48
willfarrell/alfred-pkgman-workflow pull request #152
Opened 2021-03-21 09:40 UTC by varp

2021-03-23 16:13 UTC, jeffbyrnes requested changes
A few tweaks, but otherwise this looks good!

I will say that these searches have been, and remain, broken, but that’s for another day:

* `apt-get`
* `atom/apm`
* `crates`
    * I have a fix for this I’ll ship shortly
* `gradle` - #124 
* `grunt` - #120
* `gulp`
* `pear`
* `raspbian`
* `st`
* `yo`

2021-03-29 13:51 UTC, varp commented on src/Workflows.php
> +     * @return false - XML string representation of the array
Will come back soon. I'm working on to fix all searches

2021-03-29 13:53 UTC, jeffbyrnes commented on src/Workflows.php
> +     * @return false - XML string representation of the array
Rather than tack on the fixes to this PR, I’d be happy to merge this in, and then address each of the broken searches in their own PR. But I’m good either way!

2021-04-26 15:41 UTC, varp commented
@jeffbyrnes UPDATED PR, review it please

2021-04-26 19:22 UTC, merged

2021-04-26 20:41 UTC, jeffbyrnes commented
Released as [4.0.0](https://github.com/willfarrell/alfred-pkgman-workflow/releases/tag/4.0.0)!