new separate searchers for apt-get (deb) and snap
willfarrell/alfred-pkgman-workflow pull request #169
Opened 2022-07-25 19:36 UTC by varp

- composer search do URL encode for query
- delete forgotten debug conditional - `|| 1`
- \WillFarrell\AlfredPkgMan\Workflows::read restore ability to decode in associative array

2022-07-27 16:52 UTC, jeffbyrnes requested changes

2022-07-27 16:52 UTC, jeffbyrnes commented on src/Snap.php
> +use Symfony\Component\DomCrawler\Crawler;
I did a little looking & it turns out there _is_ an API for Snaps. You can find the [docs for searching Snaps here](https://api.snapcraft.io/docs/search.html#snap_search).

It seems that the v1 API is the one to use for this. You can see an example if you request http://api.snapcraft.io/api/v1/snaps/search?q=test.

So we should be able to avoid crawling the site, and instead search programmatically!

2022-08-02 05:07 UTC, varp commented on src/Snap.php
> +use Symfony\Component\DomCrawler\Crawler;
> It seems that the v1 API is the one to use for this. 

Nice catch, it should be I missed it when I was searching Snaps site for an API. On a vacation until next Monday. Will come back and fix the PR

2022-08-25 18:10 UTC, varp commented on src/Snap.php
> +use Symfony\Component\DomCrawler\Crawler;
@jeffbyrnes I've just made changes and migrated Snap to use API. Bump version up to 6.0.1. Please review and merge if it's OK

2022-08-25 19:22 UTC, jeffbyrnes commented on src/Snap.php
> +use Symfony\Component\DomCrawler\Crawler;
I’ll take a look!

2022-08-26 15:52 UTC, jeffbyrnes approved these changes
Looks good. I think I’ll tweak this slightly so it doesn’t include the version bump, and merge it in.

2022-08-27 17:14 UTC, jeffbyrnes commented
Ended up breaking this commit up into 4 separate ones b/c it addressed 4 separate things, plus some other cleanup.

@varp this is available now & works great! Download [6.0.0](https://github.com/willfarrell/alfred-pkgman-workflow/releases/tag/6.0.0) to enjoy the fruits of your work, and thanks again.

2022-08-27 17:14 UTC, closed without merging

2022-08-28 08:27 UTC, varp commented
@jeffbyrnes You're welcome